export const PRODUCTS = [
  {
    id: 1,
    name: 'Weathercoat All Guard',
    description: 'Premium exterior emulsion with advanced weather protection',
    category: 'Exterior',
    image: IMAGES.products.exteriorAllguard,
    features: ['Weather-resistant', 'UV Protection', 'Anti-algal'],
    colors: ['#FFFFFF', '#F0F0F0', '#E5E5E5'],
  },
  {
    id: 2,
    name: 'Easy Clean Fresh',
    description: 'Interior emulsion with superior washability',
    category: 'Interior',
    image: IMAGES.products.interiorEasyClean,
    features: ['Washable', 'Low VOC', 'Stain Resistant'],
    colors: ['#FAFAFA', '#E0E0E0', '#BDBDBD'],
  },
  {
    id: 3,
    name: 'Silk Luxury Emulsion',
    description: 'Premium interior paint with luxurious silk finish',
    category: 'Interior',
    image: IMAGES.products.silkLuxury,
    features: ['Silk Finish', 'Rich Colors', 'Easy Application'],
    colors: ['#F5F5F5', '#EEEEEE', '#E0E0E0'],
  },
  {
    id: 4,
    name: 'WeatherCoat Anti Dustt',
    description: 'Exterior paint with dust-resistant technology',
    category: 'Exterior',
    image: IMAGES.products.weathercoatAntidustt,
    features: ['Dust Resistant', 'All Weather', 'Long Lasting'],
    colors: ['#FFFFFF', '#FAFAFA', '#F5F5F5'],
  },
  {
    id: 5,
    name: 'BP Wood Finish',
    description: 'Premium wood coating and varnish',
    category: 'Wood Finish',
    image: IMAGES.products.woodFinish,
    features: ['Water Resistant', 'UV Protected', 'Natural Look'],
    colors: ['#8B4513', '#A0522D', '#6B4423'],
  },
  {
    id: 6,
    name: 'Metal Coating',
    description: 'Rust-protective coating for metal surfaces',
    category: 'Metal',
    image: IMAGES.products.metalCoating,
    features: ['Rust Protection', 'Quick Dry', 'Durable'],
    colors: ['#C0C0C0', '#A9A9A9', '#808080'],
  },
]; 